name: Build BedWars1058 Plugin

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Zaktualizowano do v4 dla lepszej wydajności

      - name: Set up JDK 21
        uses: actions/setup-java@v4 # Zaktualizowano do v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install --batch-mode

      # Zaktualizowana akcja do przesyłania artefaktów
      - name: Upload Plugin JAR
        uses: actions/upload-artifact@v4 # ZMIANA: v3 -> v4
        with:
          name: BedWars1058-Plugin
          path: bedwars-plugin/target/*.jar
          if-no-files-found: error # Opcjonalne: rzuć błędem, jeśli nie znajdzie pliku .jar
